import type { Metadata } from 'next';
import { Inter, Niconne } from 'next/font/google';
import './globals.css';
import CartProvider from '@/context/cart/CartProvider';

const inter = Inter({ subsets: ['latin'] });
const niconne = Niconne({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title:
    process.env.NEXT_PUBLIC_HUSBAND_NAME +
    ' e ' +
    process.env.NEXT_PUBLIC_WIFE_NAME +
    ' vão casar!',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <head>
        <meta charSet='UTF-8' />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <link rel='preconnect' href='https://fonts.gstatic.com' />
        <link rel='stylesheet' style={niconne.style} />
      </head>
      <body className={inter.className}>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
